description:
  Object-relational database management system (ORDBMS) with an emphasis
  on extensibility and on standards-compliance. (arm32v7)
engine: gotpl
home: https://www.postgresql.org/
icon: https://www.postgresql.org/media/img/about/press/elephant.png
keywords:
  - postgresql
  - postgres
  - database
  - sql
maintainers:
  - name: swordbeta
  - name: databus23
name: postgresql
sources:
  - https://hub.docker.com/r/arm32v7/postgres/
version: 0.0.1
