{{- if .Values.service.server.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trackableappname-server" . }}
  labels:
    app: {{ template "appname-server" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "appname-server" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-server"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.application.database_url | quote }}
        - name: REDIS_URL
          value: {{ .Values.application.redis_url | quote }}
        - name: SMTP_URL
          value: {{ .Values.application.smtp_url | quote }}          
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.server.internalPort }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.server.internalPort }}
          initialDelaySeconds: 15
          timeoutSeconds: 15
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.server.internalPort }}
          initialDelaySeconds: 5
          timeoutSeconds: 3
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end -}}
